ALTER TABLE sklad DISABLE ALL TRIGGERS;
ALTER TABLE zamestnanec DISABLE ALL TRIGGERS;
ALTER TABLE skupina DISABLE ALL TRIGGERS;
ALTER TABLE karta DISABLE ALL TRIGGERS;
ALTER TABLE pohyb DISABLE ALL TRIGGERS;
ALTER TABLE presun DISABLE ALL TRIGGERS;
ALTER TABLE rola DISABLE ALL TRIGGERS;