LOAD DATA
 INFILE 'l_letenka.unl'
 INTO TABLE l_letenka
FIELDS TERMINATED BY '|'
(
 ID_LETENKY , 
 ID_LETU,
 ID_TRIEDY,
 CISLO_DOKLADU,
 TYP_DOKLADU,
 ID_ZAMESTNANCA,
 DATUM_REZERVACIE DATE 'DD.MM.YYYY' ,
 DATUM_PLATBY DATE 'DD.MM.YYYY' ,
 DATUM_ZRUSENIA DATE 'DD.MM.YYYY' ,
 CENA ,
 MIESTO       
)
     