
LOAD DATA
 INFILE 'l_let.unl'
 INTO TABLE l_let
FIELDS TERMINATED BY '|'
(
 ID_LETU   ,
 LETISKO_Z , 
 LETISKO_DO,
 ID_SPOLOCNOSTI, 
 DATUM_LETU        DATE "DD.MM.YYYY" ,
 DLZKA_LETU ,
 PLAN_CAS_ODLETU    TIMESTAMP "YYYY-MM-DD HH:MI:SS.FF",
 PLAN_CAS_PRILETU   TIMESTAMP "YYYY-MM-DD HH:MI:SS.FF",
 CENA_LETU ,
 SKUT_CAS_ODLETU    TIMESTAMP "YYYY-MM-DD HH:MI:SS.FF",
 SKUT_CAS_PRILETU   TIMESTAMP "YYYY-MM-DD HH:MI:SS.FF",
 ID_LIETADLA  
)
