PROMPT Creating Table 'LETENKAS'
CREATE TABLE LETENKAS
 (SPOSOB_PLATBY VARCHAR2(20) NOT NULL
 ,POZNAMKA VARCHAR2(35) NOT NULL
 ,CENA INTEGER NOT NULL
 ,ID INTEGER NOT NULL
 ,ZAK_ID INTEGER NOT NULL
 ,LTM_ID INTEGER NOT NULL
 ,LIE_ID INTEGER NOT NULL
 )
/

PROMPT Creating Table 'LIETADLOS'
CREATE TABLE LIETADLOS
 (CENA_TURIST INTEGER NOT NULL
 ,CENA_BUSS INTEGER NOT NULL
 ,ID INTEGER NOT NULL
 ,LS_ID INTEGER NOT NULL
 ,TL_ID INTEGER NOT NULL
 )
/

PROMPT Creating Table 'TYP_LIETADLAS'
CREATE TABLE TYP_LIETADLAS
 (ID INTEGER NOT NULL
 ,POC_MIEST INTEGER NOT NULL
 ,TYP VARCHAR2(25) NOT NULL
 )
/

PROMPT Creating Table 'LETISKOS'
CREATE TABLE LETISKOS
 (POPLATKY INTEGER NOT NULL
 ,TEL_CISLO INTEGER NOT NULL
 ,KOD VARCHAR2(15) NOT NULL
 ,NAZOV VARCHAR2(20) NOT NULL
 )
/

PROMPT Creating Table 'LET_SPOLS'
CREATE TABLE LET_SPOLS
 (ADRESA VARCHAR2(40) NOT NULL
 ,NAZOV VARCHAR2(25) NOT NULL
 ,ID INTEGER NOT NULL
 ,KONTAKT VARCHAR2(20) NOT NULL
 )
/

PROMPT Creating Table 'LETENKA_LETIES'
CREATE TABLE LETENKA_LETIES
 (CENA INTEGER NOT NULL
 ,LET_ID INTEGER NOT NULL
 ,LET1_CISLO INTEGER NOT NULL
 )
/

PROMPT Creating Table 'TYP_MIESTAS'
CREATE TABLE TYP_MIESTAS
 (ID INTEGER NOT NULL
 ,TYP VARCHAR2(10) NOT NULL
 )
/

PROMPT Creating Table 'ZAKAZNIKS'
CREATE TABLE ZAKAZNIKS
 (MENO VARCHAR2(30) NOT NULL
 ,ROD_CISLO VARCHAR2(12) NOT NULL
 ,ADRESA VARCHAR2(40) NOT NULL
 ,TEL_CISLO INTEGER NOT NULL
 ,ID INTEGER NOT NULL
 )
/

PROMPT Creating Table 'LETIES'
CREATE TABLE LETIES
 (VZDIAL_CENA_KOEF INTEGER NOT NULL
 ,ODLET_CAS DATE NOT NULL
 ,PRILET_LETISKO_KOD VARCHAR2(20) NOT NULL
 ,CISLO INTEGER NOT NULL
 ,PRILET_CAS DATE NOT NULL
 ,DATUM DATE NOT NULL
 ,ODLET_LETISKO_KOD VARCHAR2(20) NOT NULL
 ,LIE_ID INTEGER NOT NULL
 ,LS_ID INTEGER NOT NULL
 )
/

PROMPT Creating Table 'LIETADLO_TYP_MIESTAS'
CREATE TABLE LIETADLO_TYP_MIESTAS
 (ID INTEGER NOT NULL
 ,ULICKA INTEGER NOT NULL
 ,OKNO INTEGER NOT NULL
 ,STRED INTEGER NOT NULL
 ,C_MIESTA INTEGER NOT NULL
 ,TL_ID INTEGER NOT NULL
 ,TM_ID INTEGER NOT NULL
 )
/