            
               OPERACNE SYSTEMY
              ------------------

	1. Zakladne pojmy, zakladne typy OS
        2. Architektura OS

           PARALELNE PROCESY, KOMUNIKACIA MEDZI PROCESMI  
	3. Kriticke oblasti - definicia, jazykove prostriedky pre
           vyjadrenie, poziadavky pre efektivne vyuzivanie zdielanych
           prostriedkov
        4. Aktivne cakanie, pasivne cakanie, synchronizacia aktivnim cakanim,
           Dekkerov algoritmus, technicke prostriedky, ulahcujuce aktivne
           cakanie (TSL, SWAP).
        5. Vzajomne vylucovanie bez aktivneho cakania
           a) spravy, definicia, operacie nad nimi, uloha producent- 
              konzument pomocou sprav
           b) semafory, definicia, operacie nad nimi, uloha producent-
              konzument pomocou  semaforov
      	   c) monitory, definicia, operacie nad nimi, uloha producent-
              konzument pomocou monitorov
          
           SPRAVA PROCESOV
	6. Stavy procesov, cielove kriteria planovania, kvalita
           planovacieho algoritmu
        7. Planovacie algoritmy - princip, vyhody, nevyhody      
           a) Spracovanie v poradi prichodu
           b) Cyklicke planovanie
           d) Najkratsi proces najskor
           e) Najkratsi proces najskor s preempciou
	   f) Planovanie podla penalizacnej funkcie
	   g) Prioritne planovanie
	   h) Kombinovane algoritmy
	8. Uviaznutie procesov - Coffmanove podmienky
	9. Detekcia uviaznutia a zotavenie sa systemu pomocou grafu
            pridelovania prostriedkov
        10. Prevencia vzniku uviaznutia - jednorazove pridelenie,
            hierarchicke pridelovanie
        11. Dynamicka kontrola vzniku uviaznutia, algoritmus bankara

	    SPRAVA PAMATI
        12. Funkcie OP, zakladne principy pridelovania, LAP,FAP
        13. Metody dynamickej transformacie adries (DAT)
        14. Pridelenie jedineho suvisleho useku
        15. Pridelenie statickysh suvislych usekov
        17. Dynamicky tvorene suvisle useky
        18. Strankovanie -  princip, ochrana pamati, vyhody, nevyhody
    	19. Segmentacia - princip, ochrana pamati, vyhody, nevyhody
        20. Virtualizacia pamati strankovanim na ziadost, segmentovanim
            na ziadost
        
            SPRAVA PERIFERII
	21. Vyvoj a sucasny stav riadenia perifernych zariadeni
 	22. Organizacia programoveho vybavenia pre spravu periferii
        23. Ovladace perifernych zariadeni - zakl. funkcie, ovladac disku,
            ovladac terminalu
       
            SPRAVA SUBOROV
 	24. Navrh systemu suborov, priklady existujucich systemov suborov
        25. Spolahlivost systemu suborov

       

