PROMPT Creating Index 'LET_ZAK_FK_I'
CREATE INDEX LET_ZAK_FK_I ON LETENKAS
 (ZAK_ID)
/

PROMPT Creating Index 'LET_LTM_FK_I'
CREATE INDEX LET_LTM_FK_I ON LETENKAS
 (LTM_ID)
/

PROMPT Creating Index 'LET_LIE_FK_I'
CREATE INDEX LET_LIE_FK_I ON LETENKAS
 (LIE_ID)
/

PROMPT Creating Index 'LIE_LS_FK_I'
CREATE INDEX LIE_LS_FK_I ON LIETADLOS
 (LS_ID)
/

PROMPT Creating Index 'LIE_TL_FK_I'
CREATE INDEX LIE_TL_FK_I ON LIETADLOS
 (TL_ID)
/

PROMPT Creating Index 'LL_LET1_FK_I'
CREATE INDEX LL_LET1_FK_I ON LETENKA_LETIES
 (LET1_CISLO)
/

PROMPT Creating Index 'LL_LET_FK_I'
CREATE INDEX LL_LET_FK_I ON LETENKA_LETIES
 (LET_ID)
/

PROMPT Creating Index 'LET1_LIE_FK_I'
CREATE INDEX LET1_LIE_FK_I ON LETIES
 (LIE_ID)
/

PROMPT Creating Index 'LET1_LS_FK_I'
CREATE INDEX LET1_LS_FK_I ON LETIES
 (LS_ID)
/

PROMPT Creating Index 'LET1_PLK_FK_I'
CREATE INDEX LET1_LET2_FK_I ON LETIES
 (PRILET_LETISKO_KOD)
/

PROMPT Creating Index 'LET1_OLK_FK_I'
CREATE INDEX LET1_LET2_FK_II ON LETIES
 (ODLET_LETISKO_KOD)
/

PROMPT Creating Index 'LTM_TL_FK_I'
CREATE INDEX LTM_TL_FK_I ON LIETADLO_TYP_MIESTAS
 (TL_ID)
/

PROMPT Creating Index 'LTM_TM_FK_I'
CREATE INDEX LTM_TM_FK_I ON LIETADLO_TYP_MIESTAS
 (TM_ID)
/
