LOAD DATA
INFILE 'bankomat.unl'
INTO TABLE bankomat
FIELDS TERMINATED BY '|'
(
 ID_BANKOMATU
 ,TYP_BANKOMATU
 ,ID_ADRESA
 ,ROK_VYROBY
 ,DATUM_UVEDENIA DATE 'MM/DD/YYYY'
 ,DATUM_VYRADENIA DATE 'MM/DD/YYYY'
 ,GPS_SIRKA
 ,GPS_DLZKA
)