ALTER TABLE sklad ENABLE ALL TRIGGERS;
ALTER TABLE zamestnanec ENABLE ALL TRIGGERS;
ALTER TABLE skupina ENABLE ALL TRIGGERS;
ALTER TABLE karta ENABLE ALL TRIGGERS;
ALTER TABLE pohyb ENABLE ALL TRIGGERS;
ALTER TABLE presun ENABLE ALL TRIGGERS;
ALTER TABLE rola ENABLE ALL TRIGGERS;