CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_ukonov
 (id IN ZOZ_UKONOV.ID_UKONU%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_UKONOV
 WHERE ID_UKONU = id;
END Zmaz_z_zoz_ukonov;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_prijat_mat
 (id_lm IN ZOZ_PRIJAT_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
  ,id_prij IN ZOZ_PRIJAT_MAT.PRIJEM_MAT_ID_PRIJEMKA%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_PRIJAT_MAT
 WHERE ZOZ_L_A_M_ID_LIEK_A_MAT = id_lm AND PRIJEM_MAT_ID_PRIJEMKA = id_prij;
END Zmaz_z_zoz_prijat_mat;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_poist
 (id IN ZOZ_POIST.ID_POISTOVNE%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_POIST
 WHERE ID_POISTOVNE = id;
END Zmaz_z_zoz_poist;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_spot_mat_a_liekov
 (dat IN SPOT_MAT_A_LIEKOV.DAT_SPOT%TYPE
  ,id_pac IN SPOT_MAT_A_LIEKOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 )
IS
BEGIN
 DELETE FROM SPOT_MAT_A_LIEKOV
 WHERE DAT_SPOT = dat AND OS_UDAJE_P_ID_PACIENTA = id_pac;
END Zmaz_z_spot_mat_a_liekov;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_liek_a_mat
 (id IN ZOZ_LIEK_A_MAT.ID_LIEK_A_MAT%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_LIEK_A_MAT
 WHERE ID_LIEK_A_MAT = id;
END Zmaz_z_zoz_liek_a_mat;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_prijemka_materialu
 (id IN PRIJEMKA_MATERIALU.ID_PRIJEMKA%TYPE
 )
IS
BEGIN
 DELETE FROM PRIJEMKA_MATERIALU
 WHERE ID_PRIJEMKA = id;
END Zmaz_z_prijemka_materialu;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_objed_mat
 (id_lm IN ZOZ_OBJED_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
  ,id_obj IN ZOZ_OBJED_MAT.OBJED_MAT_ID_OBJEDNAVKA%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_OBJED_MAT
 WHERE ZOZ_L_A_M_ID_LIEK_A_MAT = id_lm AND OBJED_MAT_ID_OBJEDNAVKA = id_obj;
END Zmaz_z_zoz_objed_mat;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_zoz_zubov
 (zub IN ZOZ_ZUBOV.ZUB%TYPE
  ,id_pac IN ZOZ_ZUBOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 )
IS
BEGIN
 DELETE FROM ZOZ_ZUBOV
 WHERE ZUB = zub AND OS_UDAJE_P_ID_PACIENTA = id_pac;
END Zmaz_z_zoz_zubov;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_vyk_ukony
 (dat IN VYK_UKONY.DAT_VYKONU%TYPE
  ,id_pac IN VYK_UKONY.ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA%TYPE
  ,zub IN VYK_UKONY.ZOZ_ZUBOV_ZUB%TYPE
 )
IS
BEGIN
 DELETE FROM VYK_UKONY
 WHERE DAT_VYKONU = dat AND ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA =
id_pac AND ZOZ_ZUBOV_ZUB = zub;
END Zmaz_z_vyk_ukony;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_adresar_dodavatelov
 (id IN ADRESAR_DODAVATELOV.ID_ADRESAT%TYPE
 )
IS
BEGIN
 DELETE FROM ADRESAR_DODAVATELOV
 WHERE ID_ADRESAT = id;
END Zmaz_z_adresar_dodavatelov;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_objed_pacienta
 (id_pac IN OBJED_PACIENTA.OS_UDAJE_P_ID_PACIENTA%TYPE
  ,dat IN OBJED_PACIENTA.DAT_OBJEDNANIA%TYPE
 )
IS
BEGIN
 DELETE FROM OBJED_PACIENTA
 WHERE OS_UDAJE_P_ID_PACIENTA = id_pac AND DAT_OBJEDNANIA = dat;
END Zmaz_z_objed_pacienta;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_objednavka_materialu
 (id IN OBJEDNAVKA_MATERIALU.ID_OBJEDNAVKA%TYPE
 )
IS
BEGIN
 DELETE FROM OBJEDNAVKA_MATERIALU
 WHERE ID_OBJEDNAVKA = id;
END Zmaz_z_objednavka_materialu;
/

CREATE OR REPLACE PROCEDURE Zmaz_z_os_udaje_pac
 (id IN OS_UDAJE_PAC.ID_PACIENTA%TYPE
 )
IS
BEGIN
 DELETE FROM OS_UDAJE_PAC
 WHERE ID_PACIENTA = id;
END Zmaz_z_os_udaje_pac;
/
