CREATE OR REPLACE PROCEDURE Oprav_zoz_poist
 (id_pk IN ZOZ_POIST.ID_POISTOVNE%TYPE
 ,id IN ZOZ_POIST.ID_POISTOVNE%TYPE
 ,nazov IN ZOZ_POIST.NAZOV_POISTOVNE%TYPE
 )
IS
BEGIN
UPDATE ZOZ_POIST
SET ID_POISTOVNE=id,NAZOV_POISTOVNE=nazov
WHERE ID_POISTOVNE = id_pk;
END Oprav_zoz_poist;
/

CREATE OR REPLACE PROCEDURE Oprav_zoz_ukonov
 (id_pk IN ZOZ_UKONOV.ID_UKONU%TYPE
 ,id IN ZOZ_UKONOV.ID_UKONU%TYPE
 ,nazov IN ZOZ_UKONOV.POPIS_UKONU%TYPE
 ,cena IN ZOZ_UKONOV.CENA_UKONU%TYPE
 )
IS
BEGIN
UPDATE ZOZ_UKONOV
SET ID_UKONU=id,POPIS_UKONU=nazov,CENA_UKONU=cena
WHERE ID_UKONU = id_pk;
END Oprav_zoz_ukonov;
/

CREATE OR REPLACE PROCEDURE Oprav_zoz_prijat_mat
 (id_lm_pk IN ZOZ_PRIJAT_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
 ,id_prij_pk IN ZOZ_PRIJAT_MAT.PRIJEM_MAT_ID_PRIJEMKA%TYPE
 ,pocet IN ZOZ_PRIJAT_MAT.MNOZSTVO%TYPE
 ,id_lm IN ZOZ_PRIJAT_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
 ,id_prij IN ZOZ_PRIJAT_MAT.PRIJEM_MAT_ID_PRIJEMKA%TYPE
 )
IS
BEGIN
UPDATE
ZOZ_PRIJAT_MAT
SET
MNOZSTVO=pocet,ZOZ_L_A_M_ID_LIEK_A_MAT=id_lm,PRIJEM_MAT_ID_PRIJEMKA=id_prij
WHERE ZOZ_L_A_M_ID_LIEK_A_MAT = id_lm_pk AND
PRIJEM_MAT_ID_PRIJEMKA = id_prij_pk;
END Oprav_zoz_prijat_mat;
/

CREATE OR REPLACE PROCEDURE Oprav_spot_mat_a_liekov
(dat_pk IN SPOT_MAT_A_LIEKOV.DAT_SPOT%TYPE
 ,id_pac_pk IN SPOT_MAT_A_LIEKOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 ,datum IN SPOT_MAT_A_LIEKOV.DAT_SPOT%TYPE
 ,pocet IN SPOT_MAT_A_LIEKOV.POCET_JEDNOTIEK%TYPE
 ,id_pac IN SPOT_MAT_A_LIEKOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 ,id_lm IN SPOT_MAT_A_LIEKOV.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
 )
IS
BEGIN
UPDATE SPOT_MAT_A_LIEKOV
SET
DAT_SPOT=datum,POCET_JEDNOTIEK=pocet,OS_UDAJE_P_ID_PACIENTA=id_pac,ZOZ_L_A_M_ID_LIEK_A_MAT=id_lm
WHERE DAT_SPOT = dat_pk AND OS_UDAJE_P_ID_PACIENTA = id_pac_pk;
END Oprav_spot_mat_a_liekov;
/

CREATE OR REPLACE PROCEDURE Oprav_zoz_liek_a_mat
 (id_pk IN ZOZ_LIEK_A_MAT.ID_LIEK_A_MAT%TYPE
 ,id IN ZOZ_LIEK_A_MAT.ID_LIEK_A_MAT%TYPE
 ,cena IN ZOZ_LIEK_A_MAT.CENA_LIEK_A_MAT%TYPE
 ,mj IN ZOZ_LIEK_A_MAT.MJ_LIEK_A_MAT%TYPE
 ,nazov IN ZOZ_LIEK_A_MAT.NAZ_LIEK_A_MAT%TYPE
 )
IS
BEGIN
UPDATE
ZOZ_LIEK_A_MAT
SET
ID_LIEK_A_MAT=id,CENA_LIEK_A_MAT=cena,MJ_LIEK_A_MAT=mj,NAZ_LIEK_A_MAT=nazov
WHERE ID_LIEK_A_MAT = id_pk;
END Oprav_zoz_liek_a_mat;
/

CREATE OR REPLACE PROCEDURE Oprav_prijemka_materialu
 (id_prij_pk IN PRIJEMKA_MATERIALU.ID_PRIJEMKA%TYPE
 ,dat IN PRIJEMKA_MATERIALU.DAT_PRIJATIA%TYPE
 ,id_prij IN PRIJEMKA_MATERIALU.ID_PRIJEMKA%TYPE
 ,dat_platby IN PRIJEMKA_MATERIALU.DAT_PLATBY%TYPE
 ,suma IN PRIJEMKA_MATERIALU.ZAPL_SUMA%TYPE
 ,id_adr IN PRIJEMKA_MATERIALU.ADRES_DOD_ID_ADRESAT%TYPE
 ,id_obj IN PRIJEMKA_MATERIALU.OBJED_MAT_ID_OBJEDNAVKA%TYPE
 )
IS
BEGIN
UPDATE PRIJEMKA_MATERIALU
SET DAT_PRIJATIA=dat,ID_PRIJEMKA=id_prij,DAT_PLATBY=dat_platby,
 
 ZAPL_SUMA=suma,ADRES_DOD_ID_ADRESAT=id_adr,OBJED_MAT_ID_OBJEDNAVKA=id_obj
WHERE ID_PRIJEMKA = id_prij_pk;
END Oprav_prijemka_materialu;
/

CREATE OR REPLACE PROCEDURE Oprav_zoz_objed_mat
 (id_obj_pk IN ZOZ_OBJED_MAT.OBJED_MAT_ID_OBJEDNAVKA%TYPE
 ,id_lm_pk IN ZOZ_OBJED_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
 ,pocet IN ZOZ_OBJED_MAT.MNOZSTVO%TYPE
 ,id_obj IN ZOZ_OBJED_MAT.OBJED_MAT_ID_OBJEDNAVKA%TYPE
 ,id_lm IN ZOZ_OBJED_MAT.ZOZ_L_A_M_ID_LIEK_A_MAT%TYPE
 )
IS
BEGIN
UPDATE ZOZ_OBJED_MAT
SET
MNOZSTVO=pocet,OBJED_MAT_ID_OBJEDNAVKA=id_obj,ZOZ_L_A_M_ID_LIEK_A_MAT=id_lm
WHERE ZOZ_L_A_M_ID_LIEK_A_MAT = id_lm_pk AND OBJED_MAT_ID_OBJEDNAVKA =
id_obj_pk;
END Oprav_zoz_objed_mat;
/

CREATE OR REPLACE PROCEDURE Oprav_zoz_zubov
 (zub_pk IN ZOZ_ZUBOV.ZUB%TYPE
 ,id_pac_pk IN ZOZ_ZUBOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 ,stav IN ZOZ_ZUBOV.STAV_ZUBA%TYPE
 ,zub IN ZOZ_ZUBOV.ZUB%TYPE
 ,id_pac IN ZOZ_ZUBOV.OS_UDAJE_P_ID_PACIENTA%TYPE
 )
IS
BEGIN
UPDATE ZOZ_ZUBOV
SET STAV_ZUBA=stav,ZUB=zub,OS_UDAJE_P_ID_PACIENTA=id_pac
WHERE ZUB = zub_pk AND OS_UDAJE_P_ID_PACIENTA = id_pac_pk;
END Oprav_zoz_zubov;
/

CREATE OR REPLACE PROCEDURE Oprav_vyk_ukony
 (dat_ukonu_pk IN VYK_UKONY.DAT_VYKONU%TYPE
 ,id_pac_pk IN VYK_UKONY.ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA%TYPE
 ,zub_pk IN VYK_UKONY.ZOZ_ZUBOV_ZUB%TYPE
 ,dat_ukonu IN VYK_UKONY.DAT_VYKONU%TYPE
 ,dat_uhrady IN VYK_UKONY.DAT_UHRADY%TYPE
 ,id_pac IN VYK_UKONY.ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA%TYPE
 ,zub IN VYK_UKONY.ZOZ_ZUBOV_ZUB%TYPE
 ,id_ukonu IN VYK_UKONY.ZOZ_UKONOV_ID_UKONU%TYPE
 )
IS
BEGIN
UPDATE VYK_UKONY
SET DAT_VYKONU=dat_ukonu,DAT_UHRADY=dat_uhrady,ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA=id_pac,
    ZOZ_ZUBOV_ZUB=zub,ZOZ_UKONOV_ID_UKONU=id_ukonu
WHERE DAT_VYKONU = dat_ukonu_pk AND ZOZ_ZUBOOS_UDAJE_P_ID_PACIENTA =
id_pac_pk AND ZOZ_ZUBOV_ZUB = zub_pk;
END Oprav_vyk_ukony;
/

CREATE OR REPLACE PROCEDURE Oprav_adresar_dodavatelov
 (id_adr_pk IN ADRESAR_DODAVATELOV.ID_ADRESAT%TYPE
 ,dic IN ADRESAR_DODAVATELOV.DIC%TYPE
 ,obec IN ADRESAR_DODAVATELOV.OBEC%TYPE
 ,tel IN ADRESAR_DODAVATELOV.TELEFON%TYPE
 ,ulica IN ADRESAR_DODAVATELOV.ULICA%TYPE
 ,ico IN ADRESAR_DODAVATELOV.ICO%TYPE
 ,id_adr IN ADRESAR_DODAVATELOV.ID_ADRESAT%TYPE
 ,nazov IN ADRESAR_DODAVATELOV.NAZOV%TYPE
 )
IS
BEGIN
UPDATE ADRESAR_DODAVATELOV
SET
DIC=dic,OBEC=obec,TELEFON=tel,ULICA=ulica,ICO=ico,ID_ADRESAT=id_adr,NAZOV=nazov
WHERE ID_ADRESAT = id_adr_pk;
END Oprav_adresar_dodavatelov;
/

CREATE OR REPLACE PROCEDURE Oprav_objed_pacienta
 (datum_pk IN OBJED_PACIENTA.DAT_OBJEDNANIA%TYPE
 ,id_pac_pk IN OBJED_PACIENTA.OS_UDAJE_P_ID_PACIENTA%TYPE
 ,datum IN OBJED_PACIENTA.DAT_OBJEDNANIA%TYPE
 ,id_pac IN OBJED_PACIENTA.OS_UDAJE_P_ID_PACIENTA%TYPE
 ,id_ukonu IN OBJED_PACIENTA.ZOZ_UKONOV_ID_UKONU%TYPE
 )
IS
BEGIN
UPDATE
OBJED_PACIENTA
SET
DAT_OBJEDNANIA=datum,OS_UDAJE_P_ID_PACIENTA=id_pac,ZOZ_UKONOV_ID_UKONU=id_ukonu
WHERE OS_UDAJE_P_ID_PACIENTA = id_pac_pk AND DAT_OBJEDNANIA = datum_pk;
END Oprav_objed_pacienta;
/


CREATE OR REPLACE PROCEDURE Oprav_objednavka_materialu
 (id_obj_pk IN OBJEDNAVKA_MATERIALU.ID_OBJEDNAVKA%TYPE
 ,datum IN OBJEDNAVKA_MATERIALU.DAT_OBJEDNAVKY%TYPE
 ,id_obj IN OBJEDNAVKA_MATERIALU.ID_OBJEDNAVKA%TYPE
 ,dat_dod IN OBJEDNAVKA_MATERIALU.DAT_DODANIA%TYPE
 ,id_adr IN OBJEDNAVKA_MATERIALU.ADRES_DOD_ID_ADRESAT%TYPE
 )
IS
BEGIN
UPDATE
OBJEDNAVKA_MATERIALU
SET
DAT_OBJEDNAVKY=datum,ID_OBJEDNAVKA=id_obj,DAT_DODANIA=dat_dod,ADRES_DOD_ID_ADRESAT=id_adr
WHERE ID_OBJEDNAVKA = id_obj_pk;
END Oprav_objednavka_materialu;
/

CREATE OR REPLACE PROCEDURE Oprav_os_udaje_pac
 (id_pac_pk IN OS_UDAJE_PAC.ID_PACIENTA%TYPE
 ,meno IN OS_UDAJE_PAC.MENO%TYPE
 ,id_pac IN OS_UDAJE_PAC.ID_PACIENTA%TYPE
 ,dat_vyr IN OS_UDAJE_PAC.DAT_VYRADENIA%TYPE
 ,ulica IN OS_UDAJE_PAC.ADR_ULICA%TYPE
 ,obec IN OS_UDAJE_PAC.OBEC%TYPE
 ,dat_prij IN OS_UDAJE_PAC.DAT_PRIJATIA%TYPE
 ,priez IN OS_UDAJE_PAC.PRIEZVISKO%TYPE
 ,cis_poist IN OS_UDAJE_PAC.CISLO_POISTKY%TYPE
 ,id_poist IN OS_UDAJE_PAC.ZOZ_POIST_ID_POISTOVNE%TYPE
 )
IS
BEGIN
UPDATE
OS_UDAJE_PAC
SET
MENO=meno,ID_PACIENTA=id_pac,DAT_VYRADENIA=dat_vyr,ADR_ULICA=ulica,OBEC=obec,
     DAT_PRIJATIA=dat_prij,PRIEZVISKO=priez,CISLO_POISTKY=cis_poist,ZOZ_POIST_ID_POISTOVNE=id_poist
WHERE ID_PACIENTA = id_pac_pk;
END Oprav_os_udaje_pac;
/