package gui;

import datastructures.priorityFronts.EPriorityFront;
import datastructures.priorityFronts.IPriorityFront;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michal Varga
 */
public class PanelPriorityFront extends javax.swing.JPanel {

    private static final int PUSH = 0;
    private static final int POP = 1;
    private static final int PEEK = 2;
    private static final int SIZE = 5;
    private static final int CLEAR = 6; 
    
    private IPriorityFront aPriorityFront;
    private IEditData aEditData;   
    
    private void setEnabledComponents(boolean paValue) {
        btnPush.setEnabled(paValue);
        btnPop.setEnabled(paValue);
        btnPeek.setEnabled(paValue);
        btnSize.setEnabled(paValue);
        btnClear.setEnabled(paValue);
        btnTest.setEnabled(paValue);
        btnTestPush.setEnabled(paValue);
        btnTestPop.setEnabled(paValue);
    }
    
    /**
     * Creates new form PanelPriorityFront
     */
    public PanelPriorityFront() {
        initComponents();
        
        aPriorityFront = null;
        aEditData = null;
        
        setEnabledComponents(false);
        
        panelOperations.registerOperation(PUSH, "Push");
        panelOperations.registerOperation(POP, "Pop");
        panelOperations.registerOperation(PEEK, "Peek");
        panelOperations.registerOperation(SIZE, "Size");
        panelOperations.registerOperation(CLEAR, "Clear");
    }
    
    public void init(IPriorityFront paPriorityFront, IEditData paEditData) {
        aPriorityFront = paPriorityFront;
        aEditData = paEditData;
        
        Routines.listPriorityFrontElements(aPriorityFront, listElements);
        
        setEnabledComponents(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsPriorityFront = new javax.swing.JToolBar();
        lblOperationPriorityFront = new javax.swing.JLabel();
        btnPush = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        btnPeek = new javax.swing.JButton();
        btnSize = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        toolsTests = new javax.swing.JToolBar();
        lblOperationsTest = new javax.swing.JLabel();
        btnTestPush = new javax.swing.JButton();
        btnTestPop = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        panelOperations = new gui.PanelOperations();
        lblElements = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listElements = new javax.swing.JList();

        toolsPriorityFront.setRollover(true);

        lblOperationPriorityFront.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblOperationPriorityFront.setText("Operations:");
        toolsPriorityFront.add(lblOperationPriorityFront);

        btnPush.setText("Push");
        btnPush.setFocusable(false);
        btnPush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPush.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });
        toolsPriorityFront.add(btnPush);

        btnPop.setText("Pop");
        btnPop.setFocusable(false);
        btnPop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });
        toolsPriorityFront.add(btnPop);

        btnPeek.setText("Peek");
        btnPeek.setFocusable(false);
        btnPeek.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeek.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeekActionPerformed(evt);
            }
        });
        toolsPriorityFront.add(btnPeek);

        btnSize.setText("Size");
        btnSize.setFocusable(false);
        btnSize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSize.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });
        toolsPriorityFront.add(btnSize);

        btnClear.setText("Clear");
        btnClear.setFocusable(false);
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        toolsPriorityFront.add(btnClear);

        toolsTests.setRollover(true);

        lblOperationsTest.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblOperationsTest.setText("Testing:");
        toolsTests.add(lblOperationsTest);

        btnTestPush.setText("Push");
        btnTestPush.setFocusable(false);
        btnTestPush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTestPush.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTestPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestPushActionPerformed(evt);
            }
        });
        toolsTests.add(btnTestPush);

        btnTestPop.setText("Pop");
        btnTestPop.setFocusable(false);
        btnTestPop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTestPop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTestPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestPopActionPerformed(evt);
            }
        });
        toolsTests.add(btnTestPop);

        btnTest.setText("Complex test");
        btnTest.setFocusable(false);
        btnTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        toolsTests.add(btnTest);

        lblElements.setText("Elements");

        jScrollPane1.setViewportView(listElements);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolsPriorityFront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolsTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblElements)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolsPriorityFront, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolsTests, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblElements)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        try {
            Object data = aEditData.createData();
            int priority = Routines.getIntDialog("Enter priority");
            if (data != null) {  
                panelOperations.start(PUSH);
                aPriorityFront.push(data, priority);
                panelOperations.finish(PUSH,true);
            }
            else
               panelOperations.abort(PUSH,true);
        } catch (EPriorityFront ex) {
            panelOperations.except(PUSH,ex,true);
        }
        
        Routines.listPriorityFrontElements(aPriorityFront, listElements); 
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed
        try {
            if(aPriorityFront.isEmpty()) {
                panelOperations.log("Priority front is empty!");
                return;
            }
            
            panelOperations.start(POP);
            Object data = aPriorityFront.pop();
            panelOperations.finish(POP, data.toString(), true);
        } catch (EPriorityFront ex) {
            panelOperations.except(POP,ex,true);
        }
        
        Routines.listPriorityFrontElements(aPriorityFront, listElements); 
    }//GEN-LAST:event_btnPopActionPerformed

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        try { 
            panelOperations.start(SIZE);
            int size = aPriorityFront.size();        
            panelOperations.finish(SIZE,Integer.toString(size),true);
        } catch (EPriorityFront ex) {
            panelOperations.except(SIZE,ex,true);
        }
    }//GEN-LAST:event_btnSizeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        try { 
            panelOperations.start(CLEAR);
            aPriorityFront.clear();
            panelOperations.finish(CLEAR,true);
            Routines.listPriorityFrontElements(aPriorityFront, listElements);
        } catch (EPriorityFront ex) {
            panelOperations.except(CLEAR,ex,true);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeekActionPerformed
        try {
            if(aPriorityFront.isEmpty()) {
                panelOperations.log("Front is empty!");
                return;
            }
            
            panelOperations.start(PEEK);
            Object data = aPriorityFront.peek();
            panelOperations.finish(PEEK, data.toString(), true);
        } catch (EPriorityFront ex) {
            panelOperations.except(PEEK,ex,true);
        }
    }//GEN-LAST:event_btnPeekActionPerformed

    private void btnTestPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestPushActionPerformed
        try {            
            int iterations = Routines.getIntDialog("Number of iterations");
            if (iterations != -1) {
                panelOperations.start(PUSH);                
                
                for(int i = 0; i < iterations; i++) {
                    aPriorityFront.push(aEditData.createRandomData(), Routines.random(iterations));
                }                
                                
                long time = panelOperations.finish(PUSH,true); 
                panelOperations.log("Average time: " + (time/(double)iterations) + PanelOperations.UNITS);                
            }
            else
                 panelOperations.abort(PUSH,true);
        } catch (EPriorityFront ex) {
            panelOperations.except(PUSH,ex,true);
        }     
         
         Routines.listPriorityFrontElements(aPriorityFront, listElements);
    }//GEN-LAST:event_btnTestPushActionPerformed

    private void btnTestPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestPopActionPerformed
        try {            
            int iterations = Routines.getIntDialog("Number of iterations");
            if (iterations != -1) {
                panelOperations.start(POP);                
                
                iterations = iterations < aPriorityFront.size() ? iterations : aPriorityFront.size();
                
                for(int i = 0; i < iterations; i++)                     
                    aPriorityFront.pop();                
                                
                long time = panelOperations.finish(POP,true); 
                panelOperations.log("Average time: " + (time/(double)iterations) + PanelOperations.UNITS);
            }
            else
                 panelOperations.abort(POP,true);
        } catch (EPriorityFront ex) {
            panelOperations.except(POP,ex,true);
        }     
         
         Routines.listPriorityFrontElements(aPriorityFront, listElements);
    }//GEN-LAST:event_btnTestPopActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        try {                        
            int iterations = Routines.getIntDialog("Number of iterations");
            if (iterations != -1) {
                int countPush = 0;
                int countPop = 0;
                
                panelOperations.start(PUSH);                                               
                panelOperations.start(POP);
                
                panelOperations.pause(PUSH);                                               
                panelOperations.pause(POP);
                
                for(int i = 0; i < iterations; i++) {
                                                            
                    int operation = Routines.random(aPriorityFront.isEmpty() ? 1 : 2);
                    
                    switch(operation) {
                        case 0:
                            countPush++;
                            panelOperations.resume(PUSH);
                            aPriorityFront.push(aEditData.createRandomData(), iterations / 2);                            
                            panelOperations.pause(PUSH);
                            break;
                        case 1:
                            countPop++;
                            panelOperations.resume(POP);
                            aPriorityFront.pop();
                            panelOperations.pause(POP);
                            break;
                    }                                                                            
                }                
                                
                long timeAdd = panelOperations.finish(PUSH, true); 
                long timeInsert = panelOperations.finish(POP, true);
                
                DecimalFormat decFormat = new DecimalFormat( "# ###0.0000" );
                
                panelOperations.log("Number of push operations: " + countPush + " average time: " + decFormat.format(timeAdd/(double)countPush) + PanelOperations.UNITS);
                panelOperations.log("Number of pop operations: " + countPop + " average time: " + decFormat.format(timeInsert/(double)countPop) + PanelOperations.UNITS);
            }
            else {
                panelOperations.abort(PUSH,false);
                panelOperations.abort(POP,false);
            }
        } catch (EPriorityFront ex) {
            panelOperations.except(PUSH,ex,false);
            panelOperations.except(POP,ex,false);
        }     
         
         Routines.listPriorityFrontElements(aPriorityFront, listElements);
    }//GEN-LAST:event_btnTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPeek;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTestPop;
    private javax.swing.JButton btnTestPush;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElements;
    private javax.swing.JLabel lblOperationPriorityFront;
    private javax.swing.JLabel lblOperationsTest;
    private javax.swing.JList listElements;
    private gui.PanelOperations panelOperations;
    private javax.swing.JToolBar toolsPriorityFront;
    private javax.swing.JToolBar toolsTests;
    // End of variables declaration//GEN-END:variables
}
