
LOAD DATA
 INFILE 'l_zamestnanec.unl'
 INTO TABLE l_zamestnanec
FIELDS TERMINATED BY '|'
(
 ID_ZAMESTNANCA,
 ID_SPOLOCNOSTI, 
 PSC,
 CISLO_DOKLADU,
 TYP_DOKLADU,
 DATUM_PRIJATIA DATE  "DD.MM.YYYY",
 DATUM_ZRUSENIA DATE "DD.MM.YYYY",
 POZICIA,
 ROD_CISLO,
 ID_KRAJINY  
)

