var pagename=document.domain.toLowerCase().replace(/^www\./,'')+window.location.pathname+window.location.search;
_uacct = "UA-205967-3";
_uOsr[24]="idnes";	_uOkw[20]="slovo";
_uOsr[25]="atlas";	_uOkw[21]="q";
_uOsr[26]="centrum";	_uOkw[22]="q";
_uOsr[27]="dmoz";	_uOkw[23]="search";
_uOsr[28]="jyxo";	_uOkw[24]="q";
_uOsr[29]="najdi.si";	_uOkw[25]="q";
_uOsr[30]="tiscali";	_uOkw[26]="query";
_uOsr[31]="seznam";	_uOkw[27]="w";
_uOsr[32]="volny";	_uOkw[28]="search";
_uOsr[33]="yandex";	_uOkw[29]="text";
_uOsr[34]="zoohoo";	_uOkw[20]="q";
_uOsr[35]="o2active";	_uOkw[31]="o2searching";
_uOsr[36]="1.cz";	_uOkw[32]="q";
_uOsr[37]="mail.ru";	_uOkw[33]="q";
_uOsr[38]="libimseti";	_uOkw[34]="q";
_uOsr[39]="azet.sk";	_uOkw[35]="sq";
_uOsr[40]="zoznam";	_uOkw[36]="s";
_uOsr[41]="morfeo";	_uOkw[37]="q";
document.write('<img style="display:none" alt="" src="http://adv.forpsi.com/adv.php?id=2318&provid=18" width="0" height="0" border="0">');
document.write('<img style="display:none" alt="" src="http://adv.forpsi.com/adv.php?id=2319&provid=18" width="0" height="0" border="0">');
urchinTracker(pagename);
